# Generated by Django 2.1.5 on 2019-03-14 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('phoneNumber', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('plateNumber', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('xCoord', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yCoord', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(179), django.core.validators.MinValueValidator(-180)])),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('enterTime', models.TimeField()),
                ('exitTime', models.TimeField(default=models.TimeField())),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parkManagement.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('isParkingLot', models.BooleanField()),
                ('isEnter', models.BooleanField()),
                ('isExit', models.BooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nearPoint', models.IntegerField(default=0)),
                ('xCoord', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yCoord', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phoneNumber', models.IntegerField()),
                ('xCoord', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yCoord', models.DecimalField(decimal_places=4, max_digits=10)),
                ('password', models.CharField(max_length=64)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkManagement.User'),
        ),
    ]
